public class Practice12 {
    public static List<Ogrenci12> studentsList = new  List<Ogrenci12>();

    public static void students() {
        Ogrenci12 ss1 = new Ogrenci12('Esma', 'Toprak', '10B', false);
        studentsList.add(ss1);
        Ogrenci12 ss2 = new Ogrenci12('Tolga', 'Mermer', '9B', true);
        studentsList.add(ss2);
        Ogrenci12 ss3 = new Ogrenci12('Suna', 'Ozen', '11F', true);
        studentsList.add(ss3);
        Ogrenci12 ss4 = new Ogrenci12('Ali', 'Eren', '10C', false);
        studentsList.add(ss4);
    }
}
 

    

