public  class SalesforceDevoleper {
    public  void myFirstCode() {
        String favCity = ' Capadocya';
        string favMovi = 'Avatar';
        string favSeason = 'Summer';

        System.debug(favCity);
        System.debug(favMovi);
        System.debug(favSeason);
        
    }
     public void myFavorites (){
        String favCity2 = 'Rusya';
        integer favNum = 13;

        System.debug(favCity2);
        System.debug(favNum);


        
     }



    
}
