public class StudentDetails {
    public  void nameOfSutudent() {
        system.debug(' This is student information ');
        string fullName='Zeynep Karatas';
        string born ='Turkey';
        string likes = 'Shopping';
        string visit = 'India';

        system.debug('Student first and last name ' + fullName);
        system.debug('She was born in ' +  born);
        system.debug('She likes the '+ likes);
        system.debug('she really wants to visit ' + visit);

    }
}
