public with sharing class testSetDemo {
    public static void citySet() {
        // 1.creating emty set string
       
        // Datatype    variable name         Creat new instance
                                                //of list Calss
          set<string>     cities          =  new  set<string>();
        //   .add() medhod similar to LIST
        cityes.add('Isatanbul');
        cityes.add('Izmir');
        cityes.add('Irlanda');
        cityes.add('Nevsehir');
        cityes.add('Adana');
        cityes.add('Kirsehir');       
        cityes.add('Yozgat');
    
      
     } system.debug('Butun sehir isimlerini yazdir ' + cities);
        
}
