String firstVariable = ' I am the first ,okay?';
system.debug(firstVariable);

String firstName= 'zeynep'; //we are creating a new variable and assining a value to it.
String lastName = 'karatas';
String fullName = firstname + ' ' + lastName;
system.debug(' full name is ---> ' + fullName);

 firstName= 'Taha';
 lastName ='Admin';
 fullName = firstname + ' ' + lastName;
system.debug(' NOW full name is ---> ' + fullName);

